import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/lib/Providers";
import AppHeader from "@/components/AppHeader";


export const metadata: Metadata = {
  title: "News Nest",
  description: "generated by Nur Mohammad",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AppHeader />
          {children}
          <div >Footer</div>
        </Providers>
      </body>
    </html>
  );
}
